# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nathaniel Wroblewski
tagline:          "in the Machine Age"
description:      'Adventures & discovery in code. <a href="https://github.com/nathanielwroblewski" target="_blank">@nathanielwroblewski</a>.'
url:              http://nathanielwroblewski.github.io

author:
  name:           'Nathaniel Wroblewski'
  url:            https://github.com/nathanielwroblewski

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/nathanielwroblewski
